version: '3'

services:
  influxdb:
    image: influxdb:1.7.7
    networks:
      - influxdb
    ports:
      - 127.0.0.1:8086:8086
    volumes:
      - ./data/influxdb:/var/lib/influxdb
    restart: unless-stopped

  chronograf:
    image: chronograf:1.7.12
    command: chronograf --influxdb-url=http://influxdb:8086 --kapacitor-url=http://kapacitor:9092
    networks:
      - influxdb
    ports:
      - 127.0.0.1:8888:8888
    volumes:
      - ./data/chronograf:/var/lib/chronograf
    restart: unless-stopped

  kapacitor:
    image: kapacitor:1.5.3
    environment:
      - "KAPACITOR_INFLUXDB_0_URLS_0=http://influxdb:8086"
    networks:
      - influxdb
    ports:
      - 127.0.0.1:9092:9092
    volumes:
      - ./data/kapacitor:/var/lib/kapacitor
      - ./kapacitor.conf:/etc/kapacitor/kapacitor.conf:ro
    restart: unless-stopped

networks:
  influxdb:
